name: CandyMania
author: JasonHaxStuff
version: 1.5
main: me.jasonhaxstuff.candymania.Main
description: Candy in Minecraft
commands:
    bliss:
        description: "Gives you Bliss. Usage: /bliss  <amount>"
        permission: candy.give.bliss
    chocolate:
        description: "Gives you Chocolate. Usage: /chocolate  <amount>"
        permission: candy.give.chocolate
    funbar:
        description: "Gives you a FunBar. Usage: /funbar  <amount>"
        permission: candy.give.funbar
    tylenol:
        description: "Gives you Tylenol. Usage: /tylenol  <amount>"
        permission: candy.give.tylenol
    enderpop:
        description: "Gives you an EnderPop. Usage: /enderpop  <amount>"
        permission: candy.give.enderpop
    taffy:
        description: "Gives you an Taffy. Usage: /taffy  <amount>"
        permission: candy.give.taffy
    skrattar:
        description: "Gives you a Skrattar. Usage: /skrattar <amount>"
        permission: candy.give.skrattar
    prix:
        description: "Gives you Prix. Usage: /prix <amount>"
        permission: candy.give.prix